// Bilingual content for TASNED INTEGRATED (EN / AR)
export const IMAGES = {
  heroOcean: "https://images.pexels.com/photos/34155535/pexels-photo-34155535.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1200&w=1920",
  oceanSurface: "https://images.pexels.com/photos/18051278/pexels-photo-18051278.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1400",
  labScientist: "https://images.pexels.com/photos/33333666/pexels-photo-33333666/free-photo-of-massive-oil-tanker-sailing-on-open-sea.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
  tanker1: "https://images.pexels.com/photos/33333666/pexels-photo-33333666/free-photo-of-massive-oil-tanker-sailing-on-open-sea.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
  tanker2: "https://images.pexels.com/photos/19217421/pexels-photo-19217421/free-photo-of-oil-tanker-on-sea.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
  tanker3: "https://images.pexels.com/photos/38646186/pexels-photo-38646186/free-photo-of-large-lng-tanker-at-sunset-in-the-ocean.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
  labBeakers: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1400&q=80",
  cargoPort: "https://images.pexels.com/photos/16520011/pexels-photo-16520011.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1400",
  portSunset: "https://images.pexels.com/photos/35458829/pexels-photo-35458829.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1400",
  microscope: "https://images.unsplash.com/photo-1614308459036-779d0dfe51ff?auto=format&fit=crop&w=1400&q=80",
  logo: "https://customer-assets-lxgj4vgw.emergentagent.net/job_marine-testing-hub/artifacts/kut7eg12_WhatsApp%20Image%202026-08-04%20at%208.34.29%20PM.jpeg",
};

// Rotating gallery for the "Who We Are" section — analysis + tanker vessels (names not identifiable)
export const WHO_GALLERY = [
  "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1400&q=80",
  "https://images.pexels.com/photos/33333666/pexels-photo-33333666/free-photo-of-massive-oil-tanker-sailing-on-open-sea.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
  "https://images.unsplash.com/photo-1614308459036-779d0dfe51ff?auto=format&fit=crop&w=1400&q=80",
  "https://images.pexels.com/photos/19217421/pexels-photo-19217421/free-photo-of-oil-tanker-on-sea.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
  "https://images.pexels.com/photos/38646186/pexels-photo-38646186/free-photo-of-large-lng-tanker-at-sunset-in-the-ocean.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
];

const t = {
  en: {
    dir: "ltr",
    brand: "TASNED INTEGRATED",
    tagline: "Integrated Marine Solutions",
    nav: { home: "Home", about: "About", services: "Services", testing: "Ballast Water Testing", laboratory: "Laboratory", standards: "Standards", industries: "Industries", faq: "FAQ", news: "News", careers: "Careers", contact: "Contact" },
    cta: { request: "Contact Us", contact: "Our Services", learn: "Learn more", readMore: "Read more", send: "Send Message", sending: "Sending...", emergency: "Emergency Contact" },
    common: { readTime: "min read", allServices: "All Services" },
    hero: {
      eyebrow: "Independent Ballast Water Inspection & Testing Services",
      title: "Trusted Ballast Water Testing for Ships",
      subtitle: "Independent ballast water sampling and rapid, accurate analysis services supporting ship owners and operators in verifying compliance with international marine environmental regulations and standards.",
    },
    marquee: "Protecting our oceans   •   Ensuring compliance   •   Delivering solutions   •   ",
    who: {
      label: "Who We Are",
      title: "Ballast water testing and analysis for vessels",
      body: "TASNED INTEGRATED is a specialized company providing ballast water testing and analysis services for vessels. We deliver ballast water sampling and technical examination services to support ship owners, operators, and fleet managers in meeting compliance requirements under international ballast water management regulations. Our specialized services cover the complete testing process, starting from ballast water sample collection according to established procedures, followed by technical analysis, and concluding with the preparation of clear and reliable technical reports. These services help our clients evaluate ballast water conditions and make informed decisions related to vessel operations and marine compliance. Our approach is based on a structured methodology that combines technical expertise, scientific accuracy, and a strong commitment to quality and professionalism. With our dedicated focus on ballast water testing, we aim to provide reliable inspection services that meet the needs of the maritime industry and support safe vessel operations worldwide.",
    },
    servicesSection: { label: "Our Services", title: "Focused services for ballast water compliance" },
    workflow: {
      label: "How We Work", title: "Our Testing Workflow",
      steps: [
        { n: "01", t: "Inspection Request", d: "You submit vessel details and the service required. We plan attendance at the agreed port." },
        { n: "02", t: "Sampling", d: "Qualified specialists collect representative ballast water samples following accepted procedures." },
        { n: "03", t: "Onboard Rapid Screening", d: "Rapid onboard indicative analysis provides an immediate preliminary indication of compliance." },
        { n: "04", t: "Technical Report", d: "We document analytical findings in a comprehensive, traceable scientific report." },
        { n: "05", t: "Client Delivery", d: "The final report and supporting documentation are delivered to you securely." },
      ],
    },
    industriesSection: { label: "Industries Served", title: "Supporting every vessel type" },
    why: {
      label: "Why Choose TASNED", title: "Rigorous, independent, scientific",
      items: [
        { t: "Independent Testing", d: "Impartial results with no conflict of interest." },
        { t: "Qualified Specialists", d: "Trained sampling and laboratory personnel." },
        { t: "Fast Reporting", d: "Timely delivery of technical reports." },
        { t: "Reliable Results", d: "Consistent, repeatable analytical outcomes." },
        { t: "International Compliance", d: "Aligned with IMO ballast water frameworks." },
        { t: "Scientific Accuracy", d: "Controlled laboratory procedures and QC." },
        { t: "Professional Support", d: "Clear guidance throughout the process." },
      ],
    },
    counters: [
      { label: "Regulatory framework", suffix: "", value: 1, display: "IMO" },
      { label: "Compliance standard", value: 1, suffix: "", display: "D-2" },
      { label: "Vessel types served", value: 8, suffix: "+" },
    ],
    ctaBand: { title: "Your trusted partner in ballast water testing.", body: "Contact our team today for accurate, reliable, and professional maritime testing services." },
    services: [
      { icon: "Droplets", t: "Ballast Water Sampling", d: "Collection of representative ballast water samples according to accepted international procedures." },
      { icon: "Zap", t: "Indicative Analysis", d: "Rapid onboard analysis for preliminary compliance indication." },
      { icon: "ShieldCheck", t: "Compliance Verification", d: "Assessment of ballast water compliance with applicable regulations." },
      { icon: "FileText", t: "Scientific Reporting", d: "Comprehensive laboratory reports documenting analytical findings." },
      { icon: "FolderCheck", t: "Documentation Support", d: "Preparation of technical documentation related to ballast water testing activities." },
      { icon: "Ship", t: "Marine Sampling", d: "On-site marine sampling attendance coordinated with vessel operations." },
    ],
    industries: [
      { icon: "Ship", t: "Commercial Shipping" }, { icon: "Fuel", t: "Oil Tankers" },
      { icon: "Package", t: "Bulk Carriers" }, { icon: "Container", t: "Container Ships" },
      { icon: "Car", t: "Ro-Ro Vessels" }, { icon: "Users", t: "Passenger Ships" },
      { icon: "Landmark", t: "Government Fleets" }, { icon: "FlaskConical", t: "Research Ships" },
    ],
    about: {
      label: "About Us", title: "An independent marine laboratory for ballast water compliance",
      intro: "TASNED INTEGRATED exists to protect the marine environment through accurate, independent ballast water testing. We perform sampling and laboratory analysis only — providing objective evidence that helps vessels meet international requirements.",
      mission: { t: "Mission", d: "To deliver accurate, independent ballast water sampling and laboratory analysis that supports compliance and protects marine ecosystems." },
      vision: { t: "Vision", d: "To be a trusted international reference for scientific ballast water testing and marine environmental analysis." },
      valuesTitle: "Our Values",
      values: [
        { t: "Integrity", d: "Honest, impartial and transparent in every result." },
        { t: "Accuracy", d: "Precision in sampling, analysis and reporting." },
        { t: "Professionalism", d: "Reliable conduct and clear communication." },
        { t: "Scientific Excellence", d: "Sound methods and continuous rigour." },
        { t: "Environmental Protection", d: "Committed to safeguarding marine ecosystems." },
        { t: "Customer Commitment", d: "Responsive support focused on your needs." },
      ],
    },
    testing: {
      label: "Knowledge", title: "Understanding Ballast Water Testing",
      sections: [
        { t: "What is Ballast Water", d: "Ballast water is water carried in dedicated tanks to maintain a ship's stability, trim and structural integrity when cargo load changes. It is taken on and discharged as operational conditions require." },
        { t: "Why Ships Carry Ballast Water", d: "Ballast compensates for the weight of cargo. When a vessel is empty or partially loaded, ballast water keeps it balanced, submerged to a safe draft and manoeuvrable at sea." },
        { t: "Environmental Risks", d: "Ballast water taken in one region and discharged in another can transfer living organisms between ecosystems, creating ecological and economic risks in receiving waters." },
        { t: "Invasive Aquatic Species", d: "Organisms carried in ballast water can establish as invasive species, disrupting native biodiversity, fisheries and marine infrastructure." },
        { t: "Why Testing is Required", d: "Sampling and analysis provide objective evidence of the biological content of ballast water, supporting verification against international discharge standards." },
        { t: "Sampling Process", d: "Representative samples are collected using accepted procedures designed to reflect the true condition of the discharged ballast water." },
        { t: "Laboratory Examination", d: "Samples are examined under controlled laboratory conditions using microscopy and biological analysis techniques." },
        { t: "Indicative Analysis", d: "Rapid onboard indicative methods offer a preliminary indication of compliance while more detailed analysis is completed." },
        { t: "Detailed Analysis", d: "Detailed laboratory analysis quantifies viable organisms across regulated size classes under controlled conditions." },
        { t: "Compliance Reporting", d: "Findings are documented in a clear, traceable technical report suitable for compliance verification." },
        { t: "Importance of Accurate Sampling", d: "Because results depend on the representativeness of the sample, disciplined sampling technique is essential to reliable outcomes." },
        { t: "International Regulations", d: "Testing is framed by the IMO Ballast Water Management Convention and its D-2 performance standard." },
      ],
    },
    laboratory: {
      label: "Laboratory", title: "Scientific laboratory capabilities",
      intro: "Our laboratory work is dedicated to the biological examination of ballast water samples under controlled, quality-assured conditions.",
      items: [
        { icon: "Microscope", t: "Microscopy", d: "Examination of samples to identify and enumerate organisms." },
        { icon: "FlaskConical", t: "Biological Analysis", d: "Assessment of viable organisms across regulated size classes." },
        { icon: "Snowflake", t: "Sample Preservation", d: "Controlled handling and preservation to protect sample integrity." },
        { icon: "ShieldCheck", t: "Quality Control", d: "Internal quality control across the analytical workflow." },
        { icon: "GitBranch", t: "Traceability", d: "Full chain of custody from sampling to reporting." },
        { icon: "ClipboardList", t: "Analytical Procedures", d: "Defined procedures applied consistently to every sample." },
        { icon: "CheckCircle", t: "Data Validation", d: "Review and validation of analytical data before reporting." },
        { icon: "FileText", t: "Laboratory Documentation", d: "Complete documentation supporting every result." },
      ],
    },
    standards: {
      label: "Standards", title: "Regulatory standards we test against",
      intro: "Our testing supports compliance with the following internationally recognised frameworks.",
      items: [
        { t: "IMO Ballast Water Management Convention", d: "The International Convention for the Control and Management of Ships' Ballast Water and Sediments establishes global requirements for managing ballast water to prevent the spread of harmful aquatic organisms." },
        { t: "D-2 Standard", d: "The ballast water performance standard, defining limits on the concentration of viable organisms permitted in discharged ballast water." },
        { t: "Ballast Water Sampling Guidance", d: "Recognised guidance informing representative sampling of ballast water for compliance assessment." },
        { t: "Laboratory Quality Procedures", d: "Internal quality procedures governing the integrity and traceability of laboratory analysis." },
      ],
    },
    faqTitle: "Frequently Asked Questions",
    faqLabel: "FAQ",
    faqIntro: "Answers to common questions about ballast water sampling, laboratory analysis and compliance.",
    news: { label: "News", title: "News & Insights", empty: "No articles have been published yet. Please check back soon.", back: "Back to News" },
    careers: {
      label: "Careers", title: "Join TASNED INTEGRATED",
      intro: "Apply to join our specialized team supporting safe and compliant vessel operations. Complete the form below and attach your CV.",
      sections: { personal: "Personal Information", professional: "Professional Information", bioSection: "About You", uploadSection: "Upload CV" },
      form: {
        full_name: "Full Name", mobile: "Mobile Number", email: "Email",
        city: "City / Place of Residence", nationality: "Nationality (optional)",
        current_job: "Current Job Title", experience: "Years of Experience",
        sector: "Sector or Field of Expertise", qualification: "Academic Qualification",
        bio: "Brief About You",
        bioPlaceholder: "Introduce yourself and highlight your experience and skills (up to ~300 words).",
        cv: "CV / Resume", cvHint: "Accepted: PDF, DOC, DOCX — Max size: 10 MB",
        chooseFile: "Choose file", noFile: "No file selected",
        submit: "Send Application", sending: "Sending...",
        success: "Your application has been received. We will contact you if a suitable opportunity arises.",
        error: "Something went wrong. Please try again.",
        cvRequired: "Please attach your CV.",
        tooLarge: "File exceeds 10 MB.",
        invalidType: "Only PDF, DOC or DOCX files are allowed.",
      },
    },
    contact: {
      label: "Contact", title: "Contact Us",
      intro: "Have a question or need ballast water testing for your vessel? Get in touch and our specialized team will be glad to help.",
      form: { name: "Full Name", company: "Company", email: "Email", phone: "Phone", vessel_name: "Vessel Name", imo_number: "IMO Number", port: "Port", requested_service: "Service of Interest", preferred_date: "Preferred Date", message: "Message", selectService: "Select a service" },
      info: { title: "Get in touch", hoursTitle: "Availability", hours: "Available 24/7 — around-the-clock support.", addressTitle: "Location", address: "Kingdom of Saudi Arabia", emailTitle: "Email", email: "info@tasned.sa", webTitle: "Website", web: "www.tasned.sa", mapTitle: "Saudi Arabia Ports" },
      success: "Thank you for reaching out. Our team will contact you shortly.",
      error: "Something went wrong. Please try again.",
    },
    footer: { about: "Independent ballast water sampling and inspection services supporting international marine environmental compliance.", quick: "Quick Links", legal: "Legal", privacy: "Privacy Policy", terms: "Terms of Use", rights: "All rights reserved.", disclaimer: "TASNED INTEGRATED — Precision in testing, confidence in results.", crLabel: "Commercial Registration", crNumber: "7053830597" },
    admin: { login: "Admin Login", email: "Email", password: "Password", signIn: "Sign In", dashboard: "News Dashboard", new: "New Article", edit: "Edit", delete: "Delete", save: "Save", cancel: "Cancel", logout: "Logout", requests: "Inspection Requests" },
  },
  ar: {
    dir: "rtl",
    brand: "تسنيد المتكاملة",
    tagline: "حلول بحرية متكاملة",
    nav: { home: "الرئيسية", about: "من نحن", services: "الخدمات", testing: "اختبار مياه الاتزان", laboratory: "المختبر", standards: "المعايير", industries: "القطاعات", faq: "الأسئلة الشائعة", news: "الأخبار", careers: "التوظيف", contact: "اتصل بنا" },
    cta: { request: "تواصل معنا", contact: "خدماتنا", learn: "اعرف المزيد", readMore: "اقرأ المزيد", send: "إرسال الرسالة", sending: "جارٍ الإرسال...", emergency: "اتصال طارئ" },
    common: { readTime: "دقيقة قراءة", allServices: "كل الخدمات" },
    hero: {
      eyebrow: "خدمات مستقلة لفحص واختبار مياه الاتزان",
      title: "اختبار موثوق لمياه الاتزان للسفن",
      subtitle: "خدمات مستقلة لأخذ عينات مياه الاتزان وتحليلها بسرعة ودقة لدعم ملاك ومشغّلي السفن في التحقق من الامتثال للوائح والمعايير البيئية البحرية الدولية.",
    },
    marquee: "نحمي محيطاتنا   •   نضمن الامتثال   •   نقدّم الحلول   •   ",
    who: {
      label: "من نحن",
      title: "اختبار وتحليل مياه الاتزان للسفن",
      body: "تسنيد المتكاملة شركة متخصصة تقدّم خدمات اختبار وتحليل مياه الاتزان للسفن. نوفّر خدمات أخذ عينات مياه الاتزان والفحص الفني لدعم ملاك السفن والمشغّلين ومديري الأساطيل في تلبية متطلبات الامتثال بموجب اللوائح الدولية لإدارة مياه الاتزان. تغطّي خدماتنا المتخصصة عملية الاختبار الكاملة، بدءاً من جمع عينات مياه الاتزان وفق الإجراءات المعتمدة، مروراً بالتحليل الفني، وانتهاءً بإعداد تقارير فنية واضحة وموثوقة. تساعد هذه الخدمات عملاءنا على تقييم حالة مياه الاتزان واتخاذ قرارات مدروسة تتعلق بتشغيل السفن والامتثال البحري. يستند نهجنا إلى منهجية منظَّمة تجمع بين الخبرة الفنية والدقة العلمية والالتزام القوي بالجودة والاحترافية. ومع تركيزنا المكرَّس على اختبار مياه الاتزان، نهدف إلى تقديم خدمات فحص موثوقة تلبّي احتياجات القطاع البحري وتدعم تشغيل السفن بأمان حول العالم.",
    },
    servicesSection: { label: "خدماتنا", title: "خدمات متخصصة لامتثال مياه الاتزان" },
    workflow: {
      label: "طريقة عملنا", title: "مسار عمل الاختبار",
      steps: [
        { n: "01", t: "طلب الفحص", d: "ترسل بيانات السفينة والخدمة المطلوبة، ونخطّط للحضور في الميناء المتفق عليه." },
        { n: "02", t: "أخذ العينات", d: "يجمع أخصائيون مؤهلون عينات ممثِّلة لمياه الاتزان وفق الإجراءات المعتمدة." },
        { n: "03", t: "الفحص السريع على المتن", d: "يوفّر الفحص الإرشادي السريع على متن السفينة مؤشراً أولياً فورياً للامتثال." },
        { n: "04", t: "التقرير الفني", d: "نوثّق النتائج التحليلية في تقرير علمي شامل وقابل للتتبّع." },
        { n: "05", t: "التسليم للعميل", d: "يُسلَّم التقرير النهائي والوثائق الداعمة إليك بشكل آمن." },
      ],
    },
    industriesSection: { label: "القطاعات المخدومة", title: "ندعم جميع أنواع السفن" },
    why: {
      label: "لماذا تسنيد", title: "دقيق، مستقل، علمي",
      items: [
        { t: "اختبار مستقل", d: "نتائج محايدة دون تضارب مصالح." },
        { t: "أخصائيون مؤهلون", d: "كوادر مدرّبة لأخذ العينات والتحليل." },
        { t: "تقارير سريعة", d: "تسليم التقارير الفنية في وقتها." },
        { t: "نتائج موثوقة", d: "مخرجات تحليلية متسقة وقابلة للتكرار." },
        { t: "امتثال دولي", d: "متوافق مع أطر IMO لمياه الاتزان." },
        { t: "دقة علمية", d: "إجراءات مخبرية مضبوطة وضبط جودة." },
        { t: "دعم احترافي", d: "إرشاد واضح طوال العملية." },
      ],
    },
    counters: [
      { label: "إطار تنظيمي", suffix: "", value: 1, display: "IMO" },
      { label: "معيار الامتثال", value: 1, suffix: "", display: "D-2" },
      { label: "أنواع السفن المخدومة", value: 8, suffix: "+" },
    ],
    ctaBand: { title: "شريكك الموثوق في اختبار مياه الاتزان.", body: "تواصل مع فريقنا اليوم لخدمات اختبار بحرية دقيقة وموثوقة واحترافية." },
    services: [
      { icon: "Droplets", t: "أخذ عينات مياه الاتزان", d: "جمع عينات ممثِّلة لمياه الاتزان وفق الإجراءات الدولية المعتمدة." },
      { icon: "Zap", t: "التحليل الإرشادي", d: "تحليل سريع على متن السفينة لإعطاء مؤشر أولي للامتثال." },
      { icon: "ShieldCheck", t: "التحقق من الامتثال", d: "تقييم امتثال مياه الاتزان للوائح المعمول بها." },
      { icon: "FileText", t: "التقارير العلمية", d: "تقارير مخبرية شاملة توثّق النتائج التحليلية." },
      { icon: "FolderCheck", t: "دعم التوثيق", d: "إعداد الوثائق الفنية المتعلقة بأنشطة اختبار مياه الاتزان." },
      { icon: "Ship", t: "أخذ العينات البحرية", d: "حضور ميداني لأخذ العينات بالتنسيق مع عمليات السفينة." },
    ],
    industries: [
      { icon: "Ship", t: "الشحن التجاري" }, { icon: "Fuel", t: "ناقلات النفط" },
      { icon: "Package", t: "ناقلات البضائع السائبة" }, { icon: "Container", t: "سفن الحاويات" },
      { icon: "Car", t: "سفن الدحرجة" }, { icon: "Users", t: "سفن الركاب" },
      { icon: "Landmark", t: "الأساطيل الحكومية" }, { icon: "FlaskConical", t: "سفن الأبحاث" },
    ],
    about: {
      label: "من نحن", title: "مختبر بحري مستقل لامتثال مياه الاتزان",
      intro: "توجد تسنيد المتكاملة لحماية البيئة البحرية عبر اختبار دقيق ومستقل لمياه الاتزان. نقوم بأخذ العينات والتحليل المخبري فقط، مقدّمين أدلة موضوعية تساعد السفن على تلبية المتطلبات الدولية.",
      mission: { t: "الرسالة", d: "تقديم أخذ عينات وتحليل مخبري دقيق ومستقل لمياه الاتزان يدعم الامتثال ويحمي النظم البيئية البحرية." },
      vision: { t: "الرؤية", d: "أن نكون مرجعاً دولياً موثوقاً للاختبار العلمي لمياه الاتزان والتحليل البيئي البحري." },
      valuesTitle: "قيمنا",
      values: [
        { t: "النزاهة", d: "صدق وحياد وشفافية في كل نتيجة." },
        { t: "الدقة", d: "دقة في أخذ العينات والتحليل والتقارير." },
        { t: "الاحترافية", d: "سلوك موثوق وتواصل واضح." },
        { t: "التميّز العلمي", d: "منهجيات سليمة وصرامة مستمرة." },
        { t: "حماية البيئة", d: "التزام بصون النظم البيئية البحرية." },
        { t: "الالتزام تجاه العملاء", d: "دعم متجاوب يركّز على احتياجاتك." },
      ],
    },
    testing: {
      label: "المعرفة", title: "فهم اختبار مياه الاتزان",
      sections: [
        { t: "ما هي مياه الاتزان", d: "مياه الاتزان هي مياه تُحمل في خزانات مخصصة للحفاظ على اتزان السفينة وسلامتها الإنشائية عند تغيّر حمولة البضائع، تُؤخذ وتُصرَّف حسب ظروف التشغيل." },
        { t: "لماذا تحمل السفن مياه الاتزان", d: "تعوّض مياه الاتزان عن وزن البضائع؛ فعندما تكون السفينة فارغة أو محمّلة جزئياً تبقيها متوازنة وقابلة للمناورة بأمان." },
        { t: "المخاطر البيئية", d: "قد تنقل مياه الاتزان المأخوذة في منطقة والمصرَّفة في أخرى كائنات حية بين النظم البيئية، مسببة مخاطر بيئية واقتصادية." },
        { t: "الأنواع المائية الغازية", d: "قد تستقر الكائنات المنقولة عبر مياه الاتزان كأنواع غازية تخل بالتنوع الحيوي المحلي والمصايد والبنية البحرية." },
        { t: "لماذا يلزم الاختبار", d: "يوفّر أخذ العينات والتحليل دليلاً موضوعياً على المحتوى البيولوجي لمياه الاتزان لدعم التحقق مقابل معايير التصريف الدولية." },
        { t: "عملية أخذ العينات", d: "تُجمع عينات ممثِّلة بإجراءات معتمدة مصممة لتعكس الحالة الحقيقية لمياه الاتزان المصرَّفة." },
        { t: "الفحص المخبري", d: "تُفحص العينات ضمن ظروف مخبرية مضبوطة باستخدام المجهر وتقنيات التحليل البيولوجي." },
        { t: "التحليل الإرشادي", d: "توفّر الطرق الإرشادية السريعة على متن السفينة مؤشراً أولياً للامتثال ريثما يكتمل التحليل التفصيلي." },
        { t: "التحليل التفصيلي", d: "يقيس التحليل المخبري التفصيلي الكائنات الحيّة عبر فئات الأحجام المنظَّمة ضمن ظروف مضبوطة." },
        { t: "تقارير الامتثال", d: "تُوثَّق النتائج في تقرير فني واضح وقابل للتتبّع مناسب للتحقق من الامتثال." },
        { t: "أهمية دقة أخذ العينات", d: "لأن النتائج تعتمد على تمثيلية العينة، فإن انضباط أسلوب أخذ العينات ضروري لموثوقية المخرجات." },
        { t: "اللوائح الدولية", d: "يُؤطَّر الاختبار باتفاقية IMO لإدارة مياه الاتزان ومعيار الأداء D-2." },
      ],
    },
    laboratory: {
      label: "المختبر", title: "قدرات مخبرية علمية",
      intro: "يُكرَّس عمل مختبرنا للفحص البيولوجي لعينات مياه الاتزان ضمن ظروف مضبوطة ومضمونة الجودة.",
      items: [
        { icon: "Microscope", t: "الفحص المجهري", d: "فحص العينات لتحديد الكائنات وعدّها." },
        { icon: "FlaskConical", t: "التحليل البيولوجي", d: "تقييم الكائنات الحيّة عبر فئات الأحجام المنظَّمة." },
        { icon: "Snowflake", t: "حفظ العينات", d: "مناولة وحفظ مضبوطان لحماية سلامة العينة." },
        { icon: "ShieldCheck", t: "ضبط الجودة", d: "ضبط جودة داخلي عبر مسار التحليل." },
        { icon: "GitBranch", t: "قابلية التتبّع", d: "سلسلة حيازة كاملة من العينة إلى التقرير." },
        { icon: "ClipboardList", t: "الإجراءات التحليلية", d: "إجراءات محددة تُطبَّق باتساق على كل عينة." },
        { icon: "CheckCircle", t: "التحقق من البيانات", d: "مراجعة البيانات التحليلية والتحقق منها قبل التقرير." },
        { icon: "FileText", t: "التوثيق المخبري", d: "توثيق كامل يدعم كل نتيجة." },
      ],
    },
    standards: {
      label: "المعايير", title: "المعايير التنظيمية التي نختبر وفقها",
      intro: "يدعم اختبارنا الامتثال للأطر الدولية المعترف بها التالية.",
      items: [
        { t: "اتفاقية IMO لإدارة مياه الاتزان", d: "الاتفاقية الدولية لضبط وإدارة مياه اتزان السفن ورواسبها تضع متطلبات عالمية لإدارة مياه الاتزان لمنع انتشار الكائنات المائية الضارة." },
        { t: "معيار D-2", d: "معيار أداء مياه الاتزان الذي يحدد حدود تركيز الكائنات الحيّة المسموح بها في المياه المصرَّفة." },
        { t: "إرشادات أخذ عينات مياه الاتزان", d: "إرشادات معترف بها توجّه أخذ عينات ممثِّلة لمياه الاتزان لتقييم الامتثال." },
        { t: "إجراءات الجودة المخبرية", d: "إجراءات جودة داخلية تحكم سلامة وقابلية تتبّع التحليل المخبري." },
      ],
    },
    faqTitle: "الأسئلة الشائعة",
    faqLabel: "الأسئلة الشائعة",
    faqIntro: "إجابات عن الأسئلة الشائعة حول أخذ عينات مياه الاتزان والتحليل المخبري والامتثال.",
    news: { label: "الأخبار", title: "الأخبار والمقالات", empty: "لم تُنشر أي مقالات بعد. يرجى العودة قريباً.", back: "العودة للأخبار" },
    careers: {
      label: "التوظيف", title: "انضم إلى تسنيد المتكاملة",
      intro: "قدّم طلبك للانضمام إلى فريقنا المختص الذي يدعم تشغيل السفن بأمان وامتثال. أكمل النموذج أدناه وأرفق سيرتك الذاتية.",
      sections: { personal: "المعلومات الشخصية", professional: "المعلومات المهنية", bioSection: "نبذة عن المتقدم", uploadSection: "رفع الملفات" },
      form: {
        full_name: "الاسم الكامل", mobile: "رقم الجوال", email: "البريد الإلكتروني",
        city: "المدينة / مكان الإقامة", nationality: "الجنسية (اختياري)",
        current_job: "المسمى الوظيفي الحالي", experience: "سنوات الخبرة",
        sector: "القطاع أو مجال الخبرة", qualification: "المؤهل العلمي",
        bio: "نبذة مختصرة عنك",
        bioPlaceholder: "عرّف بنفسك، وأبرز خبراتك ومهاراتك في حدود 300 كلمة.",
        cv: "السيرة الذاتية", cvHint: "الصيغ المسموحة: PDF أو DOC أو DOCX — الحد الأقصى: 10 ميغابايت",
        chooseFile: "اختر ملفاً", noFile: "لم يتم اختيار ملف",
        submit: "إرسال طلب التوظيف", sending: "جارٍ الإرسال...",
        success: "تم استلام طلبك بنجاح، وسيتم التواصل معك في حال وجود فرصة مناسبة.",
        error: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
        cvRequired: "يرجى إرفاق سيرتك الذاتية.",
        tooLarge: "حجم الملف يتجاوز 10 ميغابايت.",
        invalidType: "الملفات المسموح بها هي PDF أو DOC أو DOCX فقط.",
      },
    },
    contact: {
      label: "اتصل بنا", title: "تواصل معنا",
      intro: "لديك سؤال أو تحتاج إلى اختبار مياه الاتزان لسفينتك؟ تواصل معنا وسيسعد فريقنا المختص بمساعدتك.",
      form: { name: "الاسم الكامل", company: "الشركة", email: "البريد الإلكتروني", phone: "الهاتف", vessel_name: "اسم السفينة", imo_number: "رقم IMO", port: "الميناء", requested_service: "الخدمة محل الاهتمام", preferred_date: "التاريخ المفضل", message: "الرسالة", selectService: "اختر خدمة" },
      info: { title: "تواصل معنا", hoursTitle: "التوفّر", hours: "متاحون على مدار الساعة 24/7.", addressTitle: "الموقع", address: "المملكة العربية السعودية", emailTitle: "البريد", email: "info@tasned.sa", webTitle: "الموقع الإلكتروني", web: "www.tasned.sa", mapTitle: "موانئ المملكة العربية السعودية" },
      success: "شكراً لتواصلك. سيتواصل معك فريقنا قريباً.",
      error: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    },
    footer: { about: "خدمات مستقلة لأخذ عينات وفحص مياه الاتزان لدعم الامتثال البيئي البحري الدولي.", quick: "روابط سريعة", legal: "قانوني", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام", rights: "جميع الحقوق محفوظة.", disclaimer: "تسنيد المتكاملة — دقة في الفحص، ثقة في النتائج.", crLabel: "السجل التجاري", crNumber: "7053830597" },
    admin: { login: "دخول المشرف", email: "البريد", password: "كلمة المرور", signIn: "تسجيل الدخول", dashboard: "لوحة الأخبار", new: "مقال جديد", edit: "تعديل", delete: "حذف", save: "حفظ", cancel: "إلغاء", logout: "خروج", requests: "طلبات الفحص" },
  },
};

// 30+ FAQs
export const FAQS = [
  ["What is ballast water?", "Water carried in a ship's dedicated tanks to maintain stability, trim and structural integrity.", "ما هي مياه الاتزان؟", "مياه تُحمل في خزانات مخصصة للسفينة للحفاظ على الاتزان والسلامة الإنشائية."],
  ["Why is ballast water testing required?", "To provide objective evidence that discharged ballast water meets international biological standards.", "لماذا يلزم اختبار مياه الاتزان؟", "لتقديم دليل موضوعي على أن المياه المصرَّفة تلبي المعايير البيولوجية الدولية."],
  ["What services does TASNED provide?", "Sampling, indicative analysis, detailed laboratory analysis, compliance verification, reporting and documentation support only.", "ما الخدمات التي تقدّمها تسنيد؟", "أخذ العينات والتحليل الإرشادي والتحليل المخبري التفصيلي والتحقق من الامتثال والتقارير ودعم التوثيق فقط."],
  ["Does TASNED install treatment systems?", "No. TASNED INTEGRATED performs inspection and ballast water sampling services only.", "هل تركّب تسنيد أنظمة المعالجة؟", "لا. تقوم تسنيد بالفحص وأخذ عينات مياه الاتزان فقط."],
  ["What is indicative analysis?", "A rapid onboard method giving a preliminary indication of compliance.", "ما هو التحليل الإرشادي؟", "طريقة سريعة على متن السفينة تعطي مؤشراً أولياً للامتثال."],
  ["What is detailed laboratory analysis?", "Scientific biological analysis of viable organisms performed under controlled laboratory conditions.", "ما هو التحليل المخبري التفصيلي؟", "تحليل بيولوجي علمي للكائنات الحيّة يُجرى ضمن ظروف مخبرية مضبوطة."],
  ["What is the IMO Ballast Water Management Convention?", "An international convention establishing requirements to manage ballast water and prevent the spread of harmful organisms.", "ما هي اتفاقية IMO لإدارة مياه الاتزان؟", "اتفاقية دولية تضع متطلبات لإدارة مياه الاتزان ومنع انتشار الكائنات الضارة."],
  ["What is the D-2 standard?", "The performance standard defining limits on viable organisms in discharged ballast water.", "ما هو معيار D-2؟", "معيار الأداء الذي يحدد حدود الكائنات الحيّة في المياه المصرَّفة."],
  ["How is a representative sample collected?", "Using accepted sampling procedures designed to reflect the true condition of discharged ballast water.", "كيف تُجمع العينة الممثِّلة؟", "باستخدام إجراءات معتمدة مصممة لتعكس الحالة الحقيقية للمياه المصرَّفة."],
  ["Why is representative sampling important?", "Results depend on sample representativeness, so disciplined technique is essential for reliability.", "لماذا تهم تمثيلية العينة؟", "لأن النتائج تعتمد على تمثيلية العينة، فالانضباط ضروري للموثوقية."],
  ["What organisms are assessed?", "Viable organisms across the size classes addressed by the applicable standards.", "ما الكائنات التي تُقيَّم؟", "الكائنات الحيّة عبر فئات الأحجام التي تتناولها المعايير المعمول بها."],
  ["How long does analysis take?", "Indicative results are rapid; detailed laboratory analysis timing depends on the method and sample.", "كم يستغرق التحليل؟", "النتائج الإرشادية سريعة، أما التحليل التفصيلي فيعتمد على الطريقة والعينة."],
  ["Do you attend the vessel for sampling?", "Yes, qualified specialists attend at the agreed port to collect samples.", "هل تحضرون إلى السفينة لأخذ العينات؟", "نعم، يحضر أخصائيون مؤهلون في الميناء المتفق عليه لجمع العينات."],
  ["What information do you need to plan an inspection?", "Vessel name, IMO number, port, requested service and preferred date.", "ما المعلومات اللازمة لتخطيط الفحص؟", "اسم السفينة ورقم IMO والميناء والخدمة المطلوبة والتاريخ المفضل."],
  ["Is TASNED independent?", "Yes. TASNED INTEGRATED is an independent and trusted party.", "هل تسنيد مستقلة؟", "نعم، تسنيد جهة مستقلة وموثوقة."],
  ["What is included in the report?", "A comprehensive, traceable technical report documenting the analytical findings.", "ماذا يتضمن التقرير؟", "تقرير فني شامل وقابل للتتبّع يوثّق النتائج التحليلية."],
  ["Do you provide documentation support?", "Yes, we prepare technical documentation related to ballast water testing activities.", "هل تقدّمون دعم التوثيق؟", "نعم، نُعد الوثائق الفنية المتعلقة بأنشطة اختبار مياه الاتزان."],
  ["What is chain of custody?", "The documented traceability of a sample from collection through analysis and reporting.", "ما هي سلسلة الحيازة؟", "التتبّع الموثّق للعينة من الجمع حتى التحليل والتقرير."],
  ["How are samples preserved?", "Through controlled handling and preservation to protect sample integrity before analysis.", "كيف تُحفظ العينات؟", "عبر مناولة وحفظ مضبوطين لحماية سلامة العينة قبل التحليل."],
  ["What quality controls are applied?", "Internal quality control measures are applied across the analytical workflow.", "ما ضوابط الجودة المطبَّقة؟", "تُطبَّق تدابير ضبط جودة داخلية عبر مسار التحليل."],
  ["Which vessel types do you serve?", "We serve all vessel types on request.", "ما أنواع السفن التي تخدمونها؟", "نخدم جميع أنواع السفن عند الطلب."],
  ["Can you support port State control inspections?", "We provide sampling and analysis evidence that supports compliance verification.", "هل تدعمون فحوصات رقابة دولة الميناء؟", "نوفّر أدلة أخذ العينات والتحليل التي تدعم التحقق من الامتثال."],
  ["Why are invasive species a concern?", "They can disrupt native biodiversity, fisheries and marine infrastructure in receiving waters.", "لماذا تُعد الأنواع الغازية مصدر قلق؟", "لأنها قد تخل بالتنوع الحيوي والمصايد والبنية البحرية في المياه المستقبِلة."],
  ["Do you offer onboard indicative testing?", "Yes, rapid indicative analysis can be performed onboard for a preliminary indication.", "هل تقدّمون اختباراً إرشادياً على المتن؟", "نعم، يمكن إجراء تحليل إرشادي سريع على المتن لإعطاء مؤشر أولي."],
  ["Where is TASNED based?", "TASNED INTEGRATED is based in Yanbu, Kingdom of Saudi Arabia.", "أين تقع تسنيد؟", "تقع تسنيد المتكاملة في ينبع، المملكة العربية السعودية."],
  ["How do I request an inspection?", "Complete the contact form, and our team will get back to you promptly.", "كيف أطلب فحصاً؟", "أكمل نموذج التواصل، وسيعاود فريقنا التواصل معك في أقرب وقت."],
  ["Is data kept confidential?", "Client information and results are handled with professional confidentiality.", "هل تُحفظ البيانات بسرية؟", "تُعامل معلومات العملاء والنتائج بسرية مهنية."],
  ["What standards do you test against?", "The IMO Ballast Water Management Convention, including the D-2 performance standard.", "ما المعايير التي تختبرون وفقها؟", "اتفاقية IMO لإدارة مياه الاتزان، بما في ذلك معيار الأداء D-2."],
  ["Do results guarantee compliance?", "We provide objective analytical evidence; compliance determination rests with the relevant authorities.", "هل تضمن النتائج الامتثال؟", "نقدّم أدلة تحليلية موضوعية، ويعود قرار الامتثال للجهات المختصة."],
  ["How are results validated?", "Analytical data is reviewed and validated before it is included in the final report.", "كيف يتم التحقق من النتائج؟", "تُراجَع البيانات التحليلية ويُتحقَّق منها قبل إدراجها في التقرير النهائي."],
];

export default t;

export const LEGAL = {
  privacy: {
    title: "Privacy Policy",
    intro: "TASNED INTEGRATED respects your privacy and is committed to protecting the personal information of our clients, partners, and website visitors. This Privacy Policy explains how we collect, use, protect, and manage information provided through our website and business interactions.",
    sections: [
      { h: "Information We Collect", body: "We may collect information necessary to provide our services and communicate with you, including:\n• Name, company name, job title, and contact details.\n• Any information voluntarily provided through contact forms or direct communication." },
      { h: "How We Use Your Information", body: "The information collected may be used to:\n• Respond to inquiries and service requests.\n• Provide ballast water sampling and testing services.\n• Communicate regarding scheduled activities, reports, and service updates.\n• Improve our services and customer experience." },
      { h: "Information Protection", body: "TASNED INTEGRATED applies appropriate technical and organizational measures to protect your information from unauthorized access, loss, misuse, or disclosure." },
      { h: "Information Sharing", body: "We do not sell, rent, or trade your personal information. Information may only be shared with trusted parties when necessary to deliver our services, comply with legal requirements, or fulfill contractual obligations." },
      { h: "Data Retention", body: "We retain information only for as long as necessary to fulfill the purposes for which it was collected or as required by applicable laws and regulations." },
      { h: "Your Rights", body: "You may request access, correction, or deletion of your personal information, subject to applicable legal and contractual requirements." },
      { h: "Updates to This Policy", body: "TASNED INTEGRATED may update this Privacy Policy from time to time to reflect changes in our practices or applicable regulations. Any updates will be published on this page." },
      { h: "Contact Us", body: "For any questions regarding this Privacy Policy or how we handle your information, please contact us through the official communication channels provided on our website." },
    ],
    signature: "TASNED INTEGRATED\nTrusted Maritime Services Partner",
  },
  terms: {
    title: "Terms of Use",
    intro: "Welcome to the TASNED INTEGRATED website. By accessing or using this website, you agree to comply with and be bound by these Terms of Use. Please read these terms carefully before using our website.",
    sections: [
      { h: "Acceptance of Terms", body: "By accessing this website, you acknowledge that you have read, understood, and agreed to these Terms of Use. If you do not agree with any part of these terms, please refrain from using this website." },
      { h: "Website Use", body: "This website is provided for general information about TASNED INTEGRATED, our maritime services, and our ballast water sampling and testing activities.\nYou agree to use this website only for lawful purposes and in a manner that does not infringe upon the rights of others or restrict their use of the website." },
      { h: "Services Information", body: "The information provided on this website is intended for general guidance regarding our services. TASNED INTEGRATED reserves the right to modify, update, or discontinue any information, content, or services described on this website without prior notice." },
      { h: "Intellectual Property", body: "All content owned by TASNED INTEGRATED and used on this website, including the company name and logo, is the property of TASNED INTEGRATED or is used under appropriate rights and licenses. Unauthorized use, copying, or redistribution of any content belonging to TASNED INTEGRATED is prohibited without prior approval." },
      { h: "Third-Party Links", body: "This website may contain links to third-party websites for additional information or convenience. TASNED INTEGRATED is not responsible for the content, privacy practices, or availability of these external websites." },
      { h: "Limitation of Liability", body: "While TASNED INTEGRATED strives to ensure that the information provided on this website is accurate and up to date, we do not guarantee that all information is complete, error-free, or continuously available.\nWe shall not be liable for any direct or indirect loss or damage resulting from the use of this website or reliance on its content." },
      { h: "Changes to These Terms", body: "TASNED INTEGRATED reserves the right to update or modify these Terms of Use at any time. Any changes will become effective once published on this page." },
      { h: "Governing Law and Jurisdiction", body: "These Terms of Use shall be governed by and interpreted in accordance with the laws and regulations of the Kingdom of Saudi Arabia.\nIn the event of any dispute or claim arising from the use of this website or these Terms, the competent courts in Dammam, Kingdom of Saudi Arabia, shall have jurisdiction." },
      { h: "Contact Us", body: "If you have any questions regarding these Terms of Use, please contact us through the official communication channels provided on our website." },
    ],
    signature: "TASNED INTEGRATED\nTrusted Maritime Services Partner",
  },
};
