// Bilingual content for TASNED INTEGRATED (EN / AR)
export const IMAGES = {
  heroOcean: "https://images.pexels.com/photos/34155535/pexels-photo-34155535.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1200&w=1920",
  oceanSurface: "https://images.pexels.com/photos/18051278/pexels-photo-18051278.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1400",
  labScientist: "https://images.unsplash.com/photo-1614935151651-0bea6508db6b?auto=format&fit=crop&w=1400&q=80",
  labBeakers: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1400&q=80",
  cargoPort: "https://images.pexels.com/photos/16520011/pexels-photo-16520011.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1400",
  portSunset: "https://images.pexels.com/photos/35458829/pexels-photo-35458829.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1400",
  microscope: "https://images.unsplash.com/photo-1614308459036-779d0dfe51ff?auto=format&fit=crop&w=1400&q=80",
  logo: "https://customer-assets-m6fa6gv7.emergentagent.net/job_4348158d-9201-490e-a8bc-287cf2f0eb1b/artifacts/51gl6gni_WhatsApp%20Image%202026-08-04%20at%208.34.29%20PM%20%281%29.jpeg",
};

const t = {
  en: {
    dir: "ltr",
    brand: "TASNED INTEGRATED",
    tagline: "Integrated Marine Solutions",
    nav: { home: "Home", about: "About", services: "Services", testing: "Ballast Water Testing", laboratory: "Laboratory", standards: "Standards", industries: "Industries", faq: "FAQ", news: "News", contact: "Contact" },
    cta: { request: "Request Inspection", contact: "Contact Us", learn: "Learn more", readMore: "Read more", send: "Send Request", sending: "Sending...", emergency: "Emergency Contact" },
    common: { readTime: "min read", allServices: "All Services" },
    hero: {
      eyebrow: "Independent Marine Testing Laboratory",
      title: "Trusted Ballast Water Testing & Marine Laboratory Services",
      subtitle: "Independent ballast water sampling and laboratory analysis supporting compliance with international marine environmental regulations.",
    },
    marquee: "Protecting our oceans   •   Ensuring compliance   •   Delivering solutions   •   ",
    who: {
      label: "Who We Are",
      title: "Independent ballast water sampling and laboratory analysis",
      body: "TASNED INTEGRATED is an independent marine testing laboratory dedicated exclusively to ballast water sampling and laboratory analysis. We support ship owners, operators and managers in verifying compliance with international ballast water regulations through accurate sampling, scientific examination and clear technical reporting. Our work is limited strictly to inspection, sampling and analysis — delivered with integrity and scientific rigour.",
    },
    servicesSection: { label: "Our Services", title: "Focused services for ballast water compliance" },
    workflow: {
      label: "How We Work", title: "Our Testing Workflow",
      steps: [
        { n: "01", t: "Inspection Request", d: "You submit vessel details and the service required. We plan attendance at the agreed port." },
        { n: "02", t: "Sampling", d: "Qualified specialists collect representative ballast water samples following accepted procedures." },
        { n: "03", t: "Laboratory Analysis", d: "Samples undergo indicative and detailed biological analysis under controlled conditions." },
        { n: "04", t: "Technical Report", d: "We document analytical findings in a comprehensive, traceable scientific report." },
        { n: "05", t: "Client Delivery", d: "The final report and supporting documentation are delivered to you securely." },
      ],
    },
    industriesSection: { label: "Industries Served", title: "Supporting every vessel type" },
    why: {
      label: "Why Choose TASNED", title: "Rigorous, independent, scientific",
      items: [
        { t: "Independent Testing", d: "Impartial results with no conflict of interest." },
        { t: "Qualified Specialists", d: "Trained sampling and laboratory personnel." },
        { t: "Fast Reporting", d: "Timely delivery of technical reports." },
        { t: "Reliable Results", d: "Consistent, repeatable analytical outcomes." },
        { t: "International Compliance", d: "Aligned with IMO and USCG frameworks." },
        { t: "Scientific Accuracy", d: "Controlled laboratory procedures and QC." },
        { t: "Professional Support", d: "Clear guidance throughout the process." },
      ],
    },
    counters: [
      { label: "Regulatory frameworks", suffix: "", value: 2, display: "IMO + USCG" },
      { label: "Compliance standards", value: 2, suffix: "", display: "D-1 / D-2" },
      { label: "Vessel types served", value: 8, suffix: "+" },
    ],
    ctaBand: { title: "Ready to verify your vessel's compliance?", body: "Request an inspection and our specialists will arrange sampling at your port.", },
    services: [
      { icon: "Droplets", t: "Ballast Water Sampling", d: "Collection of representative ballast water samples according to accepted international procedures." },
      { icon: "Zap", t: "Indicative Analysis", d: "Rapid onboard analysis for preliminary compliance indication." },
      { icon: "Microscope", t: "Detailed Laboratory Analysis", d: "Scientific biological analysis performed under controlled laboratory conditions." },
      { icon: "ShieldCheck", t: "Compliance Verification", d: "Assessment of ballast water compliance with applicable regulations." },
      { icon: "FileText", t: "Scientific Reporting", d: "Comprehensive laboratory reports documenting analytical findings." },
      { icon: "FolderCheck", t: "Documentation Support", d: "Preparation of technical documentation related to ballast water testing activities." },
      { icon: "Ship", t: "Marine Sampling", d: "On-site marine sampling attendance coordinated with vessel operations." },
    ],
    industries: [
      { icon: "Ship", t: "Commercial Shipping" }, { icon: "Fuel", t: "Oil Tankers" },
      { icon: "Package", t: "Bulk Carriers" }, { icon: "Container", t: "Container Ships" },
      { icon: "Car", t: "Ro-Ro Vessels" }, { icon: "Users", t: "Passenger Ships" },
      { icon: "Landmark", t: "Government Fleets" }, { icon: "FlaskConical", t: "Research Ships" },
    ],
    about: {
      label: "About Us", title: "An independent marine laboratory for ballast water compliance",
      intro: "TASNED INTEGRATED exists to protect the marine environment through accurate, independent ballast water testing. We perform sampling and laboratory analysis only — providing objective evidence that helps vessels meet international requirements.",
      mission: { t: "Mission", d: "To deliver accurate, independent ballast water sampling and laboratory analysis that supports compliance and protects marine ecosystems." },
      vision: { t: "Vision", d: "To be a trusted international reference for scientific ballast water testing and marine environmental analysis." },
      valuesTitle: "Our Values",
      values: [
        { t: "Integrity", d: "Honest, impartial and transparent in every result." },
        { t: "Accuracy", d: "Precision in sampling, analysis and reporting." },
        { t: "Professionalism", d: "Reliable conduct and clear communication." },
        { t: "Scientific Excellence", d: "Sound methods and continuous rigour." },
        { t: "Environmental Protection", d: "Committed to safeguarding marine ecosystems." },
        { t: "Customer Commitment", d: "Responsive support focused on your needs." },
      ],
    },
    testing: {
      label: "Knowledge", title: "Understanding Ballast Water Testing",
      sections: [
        { t: "What is Ballast Water", d: "Ballast water is water carried in dedicated tanks to maintain a ship's stability, trim and structural integrity when cargo load changes. It is taken on and discharged as operational conditions require." },
        { t: "Why Ships Carry Ballast Water", d: "Ballast compensates for the weight of cargo. When a vessel is empty or partially loaded, ballast water keeps it balanced, submerged to a safe draft and manoeuvrable at sea." },
        { t: "Environmental Risks", d: "Ballast water taken in one region and discharged in another can transfer living organisms between ecosystems, creating ecological and economic risks in receiving waters." },
        { t: "Invasive Aquatic Species", d: "Organisms carried in ballast water can establish as invasive species, disrupting native biodiversity, fisheries and marine infrastructure." },
        { t: "Why Testing is Required", d: "Sampling and analysis provide objective evidence of the biological content of ballast water, supporting verification against international discharge standards." },
        { t: "Sampling Process", d: "Representative samples are collected using accepted procedures designed to reflect the true condition of the discharged ballast water." },
        { t: "Laboratory Examination", d: "Samples are examined under controlled laboratory conditions using microscopy and biological analysis techniques." },
        { t: "Indicative Analysis", d: "Rapid onboard indicative methods offer a preliminary indication of compliance while more detailed analysis is completed." },
        { t: "Detailed Analysis", d: "Detailed laboratory analysis quantifies viable organisms across regulated size classes under controlled conditions." },
        { t: "Compliance Reporting", d: "Findings are documented in a clear, traceable technical report suitable for compliance verification." },
        { t: "Importance of Accurate Sampling", d: "Because results depend on the representativeness of the sample, disciplined sampling technique is essential to reliable outcomes." },
        { t: "International Regulations", d: "Testing is framed by the IMO Ballast Water Management Convention and, where applicable, US Coast Guard regulations." },
      ],
    },
    laboratory: {
      label: "Laboratory", title: "Scientific laboratory capabilities",
      intro: "Our laboratory work is dedicated to the biological examination of ballast water samples under controlled, quality-assured conditions.",
      items: [
        { icon: "Microscope", t: "Microscopy", d: "Examination of samples to identify and enumerate organisms." },
        { icon: "FlaskConical", t: "Biological Analysis", d: "Assessment of viable organisms across regulated size classes." },
        { icon: "Snowflake", t: "Sample Preservation", d: "Controlled handling and preservation to protect sample integrity." },
        { icon: "ShieldCheck", t: "Quality Control", d: "Internal quality control across the analytical workflow." },
        { icon: "GitBranch", t: "Traceability", d: "Full chain of custody from sampling to reporting." },
        { icon: "ClipboardList", t: "Analytical Procedures", d: "Defined procedures applied consistently to every sample." },
        { icon: "CheckCircle", t: "Data Validation", d: "Review and validation of analytical data before reporting." },
        { icon: "FileText", t: "Laboratory Documentation", d: "Complete documentation supporting every result." },
      ],
    },
    standards: {
      label: "Standards", title: "Regulatory standards we test against",
      intro: "Our testing supports compliance with the following internationally recognised frameworks.",
      items: [
        { t: "IMO Ballast Water Management Convention", d: "The International Convention for the Control and Management of Ships' Ballast Water and Sediments establishes global requirements for managing ballast water to prevent the spread of harmful aquatic organisms." },
        { t: "D-1 Standard", d: "The ballast water exchange standard, addressing the exchange of ballast water to reduce the transfer of coastal organisms." },
        { t: "D-2 Standard", d: "The ballast water performance standard, defining limits on the concentration of viable organisms permitted in discharged ballast water." },
        { t: "US Coast Guard Ballast Water Regulations", d: "United States requirements governing the discharge of ballast water in US waters, including applicable sampling and analysis expectations." },
        { t: "Ballast Water Sampling Guidance", d: "Recognised guidance informing representative sampling of ballast water for compliance assessment." },
        { t: "Laboratory Quality Procedures", d: "Internal quality procedures governing the integrity and traceability of laboratory analysis." },
      ],
    },
    faqTitle: "Frequently Asked Questions",
    faqLabel: "FAQ",
    faqIntro: "Answers to common questions about ballast water sampling, laboratory analysis and compliance.",
    news: { label: "News", title: "News & Insights", empty: "No articles have been published yet. Please check back soon.", back: "Back to News" },
    contact: {
      label: "Contact", title: "Request an Inspection",
      intro: "Complete the form and our specialists will arrange sampling and analysis for your vessel.",
      form: { name: "Full Name", company: "Company", email: "Email", phone: "Phone", vessel_name: "Vessel Name", imo_number: "IMO Number", port: "Port", requested_service: "Requested Service", preferred_date: "Preferred Date", message: "Message", selectService: "Select a service" },
      info: { title: "Get in touch", hoursTitle: "Business Hours", hours: "Sunday – Thursday: 08:00 – 17:00 (AST)", addressTitle: "Location", address: "Yanbu, Kingdom of Saudi Arabia", emailTitle: "Email", email: "info@tasned.sa", webTitle: "Website", web: "www.tasned.sa", mapTitle: "Find us" },
      success: "Your request has been received. Our team will contact you shortly.",
      error: "Something went wrong. Please try again.",
    },
    footer: { about: "Independent ballast water sampling and laboratory analysis supporting international marine environmental compliance.", quick: "Quick Links", legal: "Legal", privacy: "Privacy Policy", terms: "Terms of Use", rights: "All rights reserved.", disclaimer: "TASNED INTEGRATED performs inspection, sampling and laboratory analysis only." },
    admin: { login: "Admin Login", email: "Email", password: "Password", signIn: "Sign In", dashboard: "News Dashboard", new: "New Article", edit: "Edit", delete: "Delete", save: "Save", cancel: "Cancel", logout: "Logout", requests: "Inspection Requests" },
  },
  ar: {
    dir: "rtl",
    brand: "تسند المتكاملة",
    tagline: "حلول بحرية متكاملة",
    nav: { home: "الرئيسية", about: "من نحن", services: "الخدمات", testing: "اختبار مياه الاتزان", laboratory: "المختبر", standards: "المعايير", industries: "القطاعات", faq: "الأسئلة الشائعة", news: "الأخبار", contact: "اتصل بنا" },
    cta: { request: "طلب فحص", contact: "اتصل بنا", learn: "اعرف المزيد", readMore: "اقرأ المزيد", send: "إرسال الطلب", sending: "جارٍ الإرسال...", emergency: "اتصال طارئ" },
    common: { readTime: "دقيقة قراءة", allServices: "كل الخدمات" },
    hero: {
      eyebrow: "مختبر بحري مستقل للفحوصات",
      title: "خدمات موثوقة لاختبار مياه الاتزان والتحاليل المخبرية البحرية",
      subtitle: "أخذ عينات مستقل لمياه الاتزان وتحليلها مخبرياً لدعم الامتثال للوائح البيئية البحرية الدولية.",
    },
    marquee: "نحمي محيطاتنا   •   نضمن الامتثال   •   نقدّم الحلول   •   ",
    who: {
      label: "من نحن",
      title: "أخذ عينات مستقل وتحليل مخبري لمياه الاتزان",
      body: "تسند المتكاملة مختبر بحري مستقل متخصص حصرياً في أخذ عينات مياه الاتزان وتحليلها مخبرياً. ندعم ملاك ومشغّلي ومديري السفن في التحقق من الامتثال للوائح مياه الاتزان الدولية عبر أخذ عينات دقيق وفحص علمي وتقارير فنية واضحة. يقتصر عملنا على الفحص وأخذ العينات والتحليل فقط، ويُنفَّذ بنزاهة ودقة علمية.",
    },
    servicesSection: { label: "خدماتنا", title: "خدمات متخصصة لامتثال مياه الاتزان" },
    workflow: {
      label: "طريقة عملنا", title: "مسار عمل الاختبار",
      steps: [
        { n: "01", t: "طلب الفحص", d: "ترسل بيانات السفينة والخدمة المطلوبة، ونخطّط للحضور في الميناء المتفق عليه." },
        { n: "02", t: "أخذ العينات", d: "يجمع أخصائيون مؤهلون عينات ممثِّلة لمياه الاتزان وفق الإجراءات المعتمدة." },
        { n: "03", t: "التحليل المخبري", d: "تخضع العينات لتحليل إرشادي وتفصيلي بيولوجي ضمن ظروف مضبوطة." },
        { n: "04", t: "التقرير الفني", d: "نوثّق النتائج التحليلية في تقرير علمي شامل وقابل للتتبّع." },
        { n: "05", t: "التسليم للعميل", d: "يُسلَّم التقرير النهائي والوثائق الداعمة إليك بشكل آمن." },
      ],
    },
    industriesSection: { label: "القطاعات المخدومة", title: "ندعم جميع أنواع السفن" },
    why: {
      label: "لماذا تسند", title: "دقيق، مستقل، علمي",
      items: [
        { t: "اختبار مستقل", d: "نتائج محايدة دون تضارب مصالح." },
        { t: "أخصائيون مؤهلون", d: "كوادر مدرّبة لأخذ العينات والتحليل." },
        { t: "تقارير سريعة", d: "تسليم التقارير الفنية في وقتها." },
        { t: "نتائج موثوقة", d: "مخرجات تحليلية متسقة وقابلة للتكرار." },
        { t: "امتثال دولي", d: "متوافق مع أطر IMO و USCG." },
        { t: "دقة علمية", d: "إجراءات مخبرية مضبوطة وضبط جودة." },
        { t: "دعم احترافي", d: "إرشاد واضح طوال العملية." },
      ],
    },
    counters: [
      { label: "أطر تنظيمية", suffix: "", value: 2, display: "IMO + USCG" },
      { label: "معايير الامتثال", value: 2, suffix: "", display: "D-1 / D-2" },
      { label: "أنواع السفن المخدومة", value: 8, suffix: "+" },
    ],
    ctaBand: { title: "جاهز للتحقق من امتثال سفينتك؟", body: "اطلب فحصاً وسيقوم أخصائيونا بترتيب أخذ العينات في مينائك." },
    services: [
      { icon: "Droplets", t: "أخذ عينات مياه الاتزان", d: "جمع عينات ممثِّلة لمياه الاتزان وفق الإجراءات الدولية المعتمدة." },
      { icon: "Zap", t: "التحليل الإرشادي", d: "تحليل سريع على متن السفينة لإعطاء مؤشر أولي للامتثال." },
      { icon: "Microscope", t: "التحليل المخبري التفصيلي", d: "تحليل بيولوجي علمي يُجرى ضمن ظروف مخبرية مضبوطة." },
      { icon: "ShieldCheck", t: "التحقق من الامتثال", d: "تقييم امتثال مياه الاتزان للوائح المعمول بها." },
      { icon: "FileText", t: "التقارير العلمية", d: "تقارير مخبرية شاملة توثّق النتائج التحليلية." },
      { icon: "FolderCheck", t: "دعم التوثيق", d: "إعداد الوثائق الفنية المتعلقة بأنشطة اختبار مياه الاتزان." },
      { icon: "Ship", t: "أخذ العينات البحرية", d: "حضور ميداني لأخذ العينات بالتنسيق مع عمليات السفينة." },
    ],
    industries: [
      { icon: "Ship", t: "الشحن التجاري" }, { icon: "Fuel", t: "ناقلات النفط" },
      { icon: "Package", t: "ناقلات البضائع السائبة" }, { icon: "Container", t: "سفن الحاويات" },
      { icon: "Car", t: "سفن الدحرجة" }, { icon: "Users", t: "سفن الركاب" },
      { icon: "Landmark", t: "الأساطيل الحكومية" }, { icon: "FlaskConical", t: "سفن الأبحاث" },
    ],
    about: {
      label: "من نحن", title: "مختبر بحري مستقل لامتثال مياه الاتزان",
      intro: "توجد تسند المتكاملة لحماية البيئة البحرية عبر اختبار دقيق ومستقل لمياه الاتزان. نقوم بأخذ العينات والتحليل المخبري فقط، مقدّمين أدلة موضوعية تساعد السفن على تلبية المتطلبات الدولية.",
      mission: { t: "الرسالة", d: "تقديم أخذ عينات وتحليل مخبري دقيق ومستقل لمياه الاتزان يدعم الامتثال ويحمي النظم البيئية البحرية." },
      vision: { t: "الرؤية", d: "أن نكون مرجعاً دولياً موثوقاً للاختبار العلمي لمياه الاتزان والتحليل البيئي البحري." },
      valuesTitle: "قيمنا",
      values: [
        { t: "النزاهة", d: "صدق وحياد وشفافية في كل نتيجة." },
        { t: "الدقة", d: "دقة في أخذ العينات والتحليل والتقارير." },
        { t: "الاحترافية", d: "سلوك موثوق وتواصل واضح." },
        { t: "التميّز العلمي", d: "منهجيات سليمة وصرامة مستمرة." },
        { t: "حماية البيئة", d: "التزام بصون النظم البيئية البحرية." },
        { t: "الالتزام تجاه العملاء", d: "دعم متجاوب يركّز على احتياجاتك." },
      ],
    },
    testing: {
      label: "المعرفة", title: "فهم اختبار مياه الاتزان",
      sections: [
        { t: "ما هي مياه الاتزان", d: "مياه الاتزان هي مياه تُحمل في خزانات مخصصة للحفاظ على اتزان السفينة وسلامتها الإنشائية عند تغيّر حمولة البضائع، تُؤخذ وتُصرَّف حسب ظروف التشغيل." },
        { t: "لماذا تحمل السفن مياه الاتزان", d: "تعوّض مياه الاتزان عن وزن البضائع؛ فعندما تكون السفينة فارغة أو محمّلة جزئياً تبقيها متوازنة وقابلة للمناورة بأمان." },
        { t: "المخاطر البيئية", d: "قد تنقل مياه الاتزان المأخوذة في منطقة والمصرَّفة في أخرى كائنات حية بين النظم البيئية، مسببة مخاطر بيئية واقتصادية." },
        { t: "الأنواع المائية الغازية", d: "قد تستقر الكائنات المنقولة عبر مياه الاتزان كأنواع غازية تخل بالتنوع الحيوي المحلي والمصايد والبنية البحرية." },
        { t: "لماذا يلزم الاختبار", d: "يوفّر أخذ العينات والتحليل دليلاً موضوعياً على المحتوى البيولوجي لمياه الاتزان لدعم التحقق مقابل معايير التصريف الدولية." },
        { t: "عملية أخذ العينات", d: "تُجمع عينات ممثِّلة بإجراءات معتمدة مصممة لتعكس الحالة الحقيقية لمياه الاتزان المصرَّفة." },
        { t: "الفحص المخبري", d: "تُفحص العينات ضمن ظروف مخبرية مضبوطة باستخدام المجهر وتقنيات التحليل البيولوجي." },
        { t: "التحليل الإرشادي", d: "توفّر الطرق الإرشادية السريعة على متن السفينة مؤشراً أولياً للامتثال ريثما يكتمل التحليل التفصيلي." },
        { t: "التحليل التفصيلي", d: "يقيس التحليل المخبري التفصيلي الكائنات الحيّة عبر فئات الأحجام المنظَّمة ضمن ظروف مضبوطة." },
        { t: "تقارير الامتثال", d: "تُوثَّق النتائج في تقرير فني واضح وقابل للتتبّع مناسب للتحقق من الامتثال." },
        { t: "أهمية دقة أخذ العينات", d: "لأن النتائج تعتمد على تمثيلية العينة، فإن انضباط أسلوب أخذ العينات ضروري لموثوقية المخرجات." },
        { t: "اللوائح الدولية", d: "يُؤطَّر الاختبار باتفاقية IMO لإدارة مياه الاتزان، وعند الاقتضاء لوائح خفر السواحل الأمريكي." },
      ],
    },
    laboratory: {
      label: "المختبر", title: "قدرات مخبرية علمية",
      intro: "يُكرَّس عمل مختبرنا للفحص البيولوجي لعينات مياه الاتزان ضمن ظروف مضبوطة ومضمونة الجودة.",
      items: [
        { icon: "Microscope", t: "الفحص المجهري", d: "فحص العينات لتحديد الكائنات وعدّها." },
        { icon: "FlaskConical", t: "التحليل البيولوجي", d: "تقييم الكائنات الحيّة عبر فئات الأحجام المنظَّمة." },
        { icon: "Snowflake", t: "حفظ العينات", d: "مناولة وحفظ مضبوطان لحماية سلامة العينة." },
        { icon: "ShieldCheck", t: "ضبط الجودة", d: "ضبط جودة داخلي عبر مسار التحليل." },
        { icon: "GitBranch", t: "قابلية التتبّع", d: "سلسلة حيازة كاملة من العينة إلى التقرير." },
        { icon: "ClipboardList", t: "الإجراءات التحليلية", d: "إجراءات محددة تُطبَّق باتساق على كل عينة." },
        { icon: "CheckCircle", t: "التحقق من البيانات", d: "مراجعة البيانات التحليلية والتحقق منها قبل التقرير." },
        { icon: "FileText", t: "التوثيق المخبري", d: "توثيق كامل يدعم كل نتيجة." },
      ],
    },
    standards: {
      label: "المعايير", title: "المعايير التنظيمية التي نختبر وفقها",
      intro: "يدعم اختبارنا الامتثال للأطر الدولية المعترف بها التالية.",
      items: [
        { t: "اتفاقية IMO لإدارة مياه الاتزان", d: "الاتفاقية الدولية لضبط وإدارة مياه اتزان السفن ورواسبها تضع متطلبات عالمية لإدارة مياه الاتزان لمنع انتشار الكائنات المائية الضارة." },
        { t: "معيار D-1", d: "معيار تبادل مياه الاتزان الذي يتناول تبادل المياه لتقليل نقل الكائنات الساحلية." },
        { t: "معيار D-2", d: "معيار أداء مياه الاتزان الذي يحدد حدود تركيز الكائنات الحيّة المسموح بها في المياه المصرَّفة." },
        { t: "لوائح خفر السواحل الأمريكي", d: "متطلبات الولايات المتحدة التي تحكم تصريف مياه الاتزان في المياه الأمريكية، بما فيها توقعات أخذ العينات والتحليل." },
        { t: "إرشادات أخذ عينات مياه الاتزان", d: "إرشادات معترف بها توجّه أخذ عينات ممثِّلة لمياه الاتزان لتقييم الامتثال." },
        { t: "إجراءات الجودة المخبرية", d: "إجراءات جودة داخلية تحكم سلامة وقابلية تتبّع التحليل المخبري." },
      ],
    },
    faqTitle: "الأسئلة الشائعة",
    faqLabel: "الأسئلة الشائعة",
    faqIntro: "إجابات عن الأسئلة الشائعة حول أخذ عينات مياه الاتزان والتحليل المخبري والامتثال.",
    news: { label: "الأخبار", title: "الأخبار والمقالات", empty: "لم تُنشر أي مقالات بعد. يرجى العودة قريباً.", back: "العودة للأخبار" },
    contact: {
      label: "اتصل بنا", title: "طلب فحص",
      intro: "أكمل النموذج وسيقوم أخصائيونا بترتيب أخذ العينات والتحليل لسفينتك.",
      form: { name: "الاسم الكامل", company: "الشركة", email: "البريد الإلكتروني", phone: "الهاتف", vessel_name: "اسم السفينة", imo_number: "رقم IMO", port: "الميناء", requested_service: "الخدمة المطلوبة", preferred_date: "التاريخ المفضل", message: "الرسالة", selectService: "اختر خدمة" },
      info: { title: "تواصل معنا", hoursTitle: "ساعات العمل", hours: "الأحد – الخميس: 08:00 – 17:00 (توقيت السعودية)", addressTitle: "الموقع", address: "ينبع، المملكة العربية السعودية", emailTitle: "البريد", email: "info@tasned.sa", webTitle: "الموقع الإلكتروني", web: "www.tasned.sa", mapTitle: "موقعنا" },
      success: "تم استلام طلبك. سيتواصل فريقنا معك قريباً.",
      error: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    },
    footer: { about: "أخذ عينات مستقل وتحليل مخبري لمياه الاتزان لدعم الامتثال البيئي البحري الدولي.", quick: "روابط سريعة", legal: "قانوني", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام", rights: "جميع الحقوق محفوظة.", disclaimer: "تقوم تسند المتكاملة بالفحص وأخذ العينات والتحليل المخبري فقط." },
    admin: { login: "دخول المشرف", email: "البريد", password: "كلمة المرور", signIn: "تسجيل الدخول", dashboard: "لوحة الأخبار", new: "مقال جديد", edit: "تعديل", delete: "حذف", save: "حفظ", cancel: "إلغاء", logout: "خروج", requests: "طلبات الفحص" },
  },
};

// 30+ FAQs
export const FAQS = [
  ["What is ballast water?", "Water carried in a ship's dedicated tanks to maintain stability, trim and structural integrity.", "ما هي مياه الاتزان؟", "مياه تُحمل في خزانات مخصصة للسفينة للحفاظ على الاتزان والسلامة الإنشائية."],
  ["Why is ballast water testing required?", "To provide objective evidence that discharged ballast water meets international biological standards.", "لماذا يلزم اختبار مياه الاتزان؟", "لتقديم دليل موضوعي على أن المياه المصرَّفة تلبي المعايير البيولوجية الدولية."],
  ["What services does TASNED provide?", "Sampling, indicative analysis, detailed laboratory analysis, compliance verification, reporting and documentation support only.", "ما الخدمات التي تقدّمها تسند؟", "أخذ العينات والتحليل الإرشادي والتحليل المخبري التفصيلي والتحقق من الامتثال والتقارير ودعم التوثيق فقط."],
  ["Does TASNED install treatment systems?", "No. TASNED performs inspection, sampling and laboratory analysis only.", "هل تركّب تسند أنظمة المعالجة؟", "لا. تقوم تسند بالفحص وأخذ العينات والتحليل المخبري فقط."],
  ["What is indicative analysis?", "A rapid onboard method giving a preliminary indication of compliance.", "ما هو التحليل الإرشادي؟", "طريقة سريعة على متن السفينة تعطي مؤشراً أولياً للامتثال."],
  ["What is detailed laboratory analysis?", "Scientific biological analysis of viable organisms performed under controlled laboratory conditions.", "ما هو التحليل المخبري التفصيلي؟", "تحليل بيولوجي علمي للكائنات الحيّة يُجرى ضمن ظروف مخبرية مضبوطة."],
  ["What is the IMO Ballast Water Management Convention?", "An international convention establishing requirements to manage ballast water and prevent the spread of harmful organisms.", "ما هي اتفاقية IMO لإدارة مياه الاتزان؟", "اتفاقية دولية تضع متطلبات لإدارة مياه الاتزان ومنع انتشار الكائنات الضارة."],
  ["What is the D-1 standard?", "The ballast water exchange standard aimed at reducing transfer of coastal organisms.", "ما هو معيار D-1؟", "معيار تبادل مياه الاتزان الذي يهدف لتقليل نقل الكائنات الساحلية."],
  ["What is the D-2 standard?", "The performance standard defining limits on viable organisms in discharged ballast water.", "ما هو معيار D-2؟", "معيار الأداء الذي يحدد حدود الكائنات الحيّة في المياه المصرَّفة."],
  ["Do US Coast Guard regulations apply to my vessel?", "They apply to ballast water discharge in US waters; applicability depends on your trading area.", "هل تنطبق لوائح خفر السواحل الأمريكي على سفينتي؟", "تنطبق على تصريف المياه في المياه الأمريكية، ويعتمد ذلك على منطقة تشغيلك."],
  ["How is a representative sample collected?", "Using accepted sampling procedures designed to reflect the true condition of discharged ballast water.", "كيف تُجمع العينة الممثِّلة؟", "باستخدام إجراءات معتمدة مصممة لتعكس الحالة الحقيقية للمياه المصرَّفة."],
  ["Why is representative sampling important?", "Results depend on sample representativeness, so disciplined technique is essential for reliability.", "لماذا تهم تمثيلية العينة؟", "لأن النتائج تعتمد على تمثيلية العينة، فالانضباط ضروري للموثوقية."],
  ["What organisms are assessed?", "Viable organisms across the size classes addressed by the applicable standards.", "ما الكائنات التي تُقيَّم؟", "الكائنات الحيّة عبر فئات الأحجام التي تتناولها المعايير المعمول بها."],
  ["How long does analysis take?", "Indicative results are rapid; detailed laboratory analysis timing depends on the method and sample.", "كم يستغرق التحليل؟", "النتائج الإرشادية سريعة، أما التحليل التفصيلي فيعتمد على الطريقة والعينة."],
  ["Do you attend the vessel for sampling?", "Yes, qualified specialists attend at the agreed port to collect samples.", "هل تحضرون إلى السفينة لأخذ العينات؟", "نعم، يحضر أخصائيون مؤهلون في الميناء المتفق عليه لجمع العينات."],
  ["What information do you need to plan an inspection?", "Vessel name, IMO number, port, requested service and preferred date.", "ما المعلومات اللازمة لتخطيط الفحص؟", "اسم السفينة ورقم IMO والميناء والخدمة المطلوبة والتاريخ المفضل."],
  ["Is TASNED independent?", "Yes. We provide impartial testing with no conflict of interest.", "هل تسند مستقلة؟", "نعم، نقدّم اختباراً محايداً دون تضارب مصالح."],
  ["What is included in the report?", "A comprehensive, traceable technical report documenting the analytical findings.", "ماذا يتضمن التقرير؟", "تقرير فني شامل وقابل للتتبّع يوثّق النتائج التحليلية."],
  ["Do you provide documentation support?", "Yes, we prepare technical documentation related to ballast water testing activities.", "هل تقدّمون دعم التوثيق؟", "نعم، نُعد الوثائق الفنية المتعلقة بأنشطة اختبار مياه الاتزان."],
  ["What is chain of custody?", "The documented traceability of a sample from collection through analysis and reporting.", "ما هي سلسلة الحيازة؟", "التتبّع الموثّق للعينة من الجمع حتى التحليل والتقرير."],
  ["How are samples preserved?", "Through controlled handling and preservation to protect sample integrity before analysis.", "كيف تُحفظ العينات؟", "عبر مناولة وحفظ مضبوطين لحماية سلامة العينة قبل التحليل."],
  ["What quality controls are applied?", "Internal quality control measures are applied across the analytical workflow.", "ما ضوابط الجودة المطبَّقة؟", "تُطبَّق تدابير ضبط جودة داخلية عبر مسار التحليل."],
  ["Which vessel types do you serve?", "Commercial shipping, tankers, bulk carriers, container ships, Ro-Ro, passenger ships, government and research vessels.", "ما أنواع السفن التي تخدمونها؟", "الشحن التجاري والناقلات وناقلات البضائع السائبة وسفن الحاويات والدحرجة والركاب والسفن الحكومية والبحثية."],
  ["Can you support port State control inspections?", "We provide sampling and analysis evidence that supports compliance verification.", "هل تدعمون فحوصات رقابة دولة الميناء؟", "نوفّر أدلة أخذ العينات والتحليل التي تدعم التحقق من الامتثال."],
  ["Why are invasive species a concern?", "They can disrupt native biodiversity, fisheries and marine infrastructure in receiving waters.", "لماذا تُعد الأنواع الغازية مصدر قلق؟", "لأنها قد تخل بالتنوع الحيوي والمصايد والبنية البحرية في المياه المستقبِلة."],
  ["Do you offer onboard indicative testing?", "Yes, rapid indicative analysis can be performed onboard for a preliminary indication.", "هل تقدّمون اختباراً إرشادياً على المتن؟", "نعم، يمكن إجراء تحليل إرشادي سريع على المتن لإعطاء مؤشر أولي."],
  ["Where is TASNED based?", "TASNED INTEGRATED is based in Yanbu, Kingdom of Saudi Arabia.", "أين تقع تسند؟", "تقع تسند المتكاملة في ينبع، المملكة العربية السعودية."],
  ["How do I request an inspection?", "Complete the contact form with your vessel details and requested service.", "كيف أطلب فحصاً؟", "أكمل نموذج الاتصال ببيانات سفينتك والخدمة المطلوبة."],
  ["Is data kept confidential?", "Client information and results are handled with professional confidentiality.", "هل تُحفظ البيانات بسرية؟", "تُعامل معلومات العملاء والنتائج بسرية مهنية."],
  ["What standards do you test against?", "The IMO Ballast Water Management Convention (D-1/D-2) and, where applicable, US Coast Guard regulations.", "ما المعايير التي تختبرون وفقها؟", "اتفاقية IMO لإدارة مياه الاتزان (D-1/D-2) وعند الاقتضاء لوائح خفر السواحل الأمريكي."],
  ["Do results guarantee compliance?", "We provide objective analytical evidence; compliance determination rests with the relevant authorities.", "هل تضمن النتائج الامتثال؟", "نقدّم أدلة تحليلية موضوعية، ويعود قرار الامتثال للجهات المختصة."],
  ["How are results validated?", "Analytical data is reviewed and validated before it is included in the final report.", "كيف يتم التحقق من النتائج؟", "تُراجَع البيانات التحليلية ويُتحقَّق منها قبل إدراجها في التقرير النهائي."],
];

export default t;
